package ru.qa.armada.n03_applicationStructure.n01_RadioMonitoring.n01_Tasks.n01_creatingAndEditingMonitoringTask.n02_frequincies.n02_bookmarkFrequencies;

public class SelectionOfRadiationSources {
}
